import {chromium} from 'playwright-core';
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const b=await chromium.launch({executablePath:CHROME,headless:true,args:['--no-sandbox','--force-color-profile=srgb']});
const ctx=await b.newContext({viewport:{width:1650,height:1200},deviceScaleFactor:2});
const p=await ctx.newPage();
await p.goto('file://'+process.cwd()+'/landscape.html',{waitUntil:'networkidle'});
await p.waitForTimeout(400);
const el=await p.$('#root');
await el.screenshot({path:'shots/00-landscape.png'});
const box=await el.boundingBox();
console.log('rendered', Math.round(box.width)+'x'+Math.round(box.height), '@2x');
await b.close();
